# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transcriber < Formula
  desc "CLI tool to transcribe audio files via OpenAI Whisper"
  homepage "https://github.com/IgorSakharov/transcriber"
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.0/transcriber_darwin_amd64.tar.gz"
    sha256 "e3a38dfe1029aefe243477cd43750434c3613cb2029806eb2fe5a932c77d8deb"

    define_method(:install) do
      bin.install "transcriber"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.0/transcriber_darwin_arm64.tar.gz"
    sha256 "f5213a6a52efd23ec4e185083cbc9435bdcda04920b287f4704713403356c65d"

    define_method(:install) do
      bin.install "transcriber"
    end
  end

  test do
    system "#{bin}/transcriber", "--help"
  end
end
