# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transcriber < Formula
  desc "CLI tool to transcribe audio files via OpenAI Whisper"
  homepage "https://github.com/IgorSakharov/transcriber"
  version "1.0.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.1/transcriber_darwin_amd64.tar.gz"
    sha256 "2a9866b50efeb67e208768a0b4643e1849ce9cb62a59eded3fb47d47c95b9f30"

    define_method(:install) do
      bin.install "transcriber"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.1/transcriber_darwin_arm64.tar.gz"
    sha256 "13d5fd6fdf1b5824d8dcc2d152f7dbdfb6f8eeed665d896d16ca16ea4ba5960d"

    define_method(:install) do
      bin.install "transcriber"
    end
  end

  test do
    system "#{bin}/transcriber", "--help"
  end
end
