# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transcriber < Formula
  desc "CLI tool to transcribe audio files via OpenAI Whisper"
  homepage "https://github.com/IgorSakharov/transcriber"
  version "1.0.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.3/transcriber_darwin_amd64.tar.gz"
    sha256 "eb95726a5dedcf0686b2c3407f4b8cff76e5474b1849e50e9dd047941153278e"

    define_method(:install) do
      bin.install "transcriber"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.3/transcriber_darwin_arm64.tar.gz"
    sha256 "5e94e465c330630e677186267b27c044f906714a0bc2bbd75fa4a400051ce8e2"

    define_method(:install) do
      bin.install "transcriber"
    end
  end

  test do
    system "#{bin}/transcriber", "--help"
  end
end
