# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transcriber < Formula
  desc "CLI tool to transcribe audio files via OpenAI Whisper"
  homepage "https://github.com/IgorSakharov/transcriber"
  version "1.0.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.2/transcriber_darwin_amd64.tar.gz"
    sha256 "fe783d25ce53edd44ec03cdcca4a3d47798e9e4b615c0e848a9715e6dda3a8af"

    define_method(:install) do
      bin.install "transcriber"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/IgorSakharov/transcriber/releases/download/v1.0.2/transcriber_darwin_arm64.tar.gz"
    sha256 "65663a60f52873313d81294c1b8c9c90a76805ad48336e4c0749d5025bfd8e55"

    define_method(:install) do
      bin.install "transcriber"
    end
  end

  test do
    system "#{bin}/transcriber", "--help"
  end
end
